## Objective: Learning to solve basic Python problems

Prerequisites: Module 1 listed @ https://www.appliedaicourse.com/course/11/Applied-Machine-learning-course - SQL

Tackle few simple problems relvant to AI/ML
    - Break a problem into smaller sub-problems.
    - Connecting the dots from sub-problems to coding-concepts.
    - Code-walkthrough + Putting it all together.
    - More focus on common errors and mistakes + reading function reference + fixing bugs
    - Exercise-problems for practice.
    - Introduce new concepts as we need.
    - Good programmers may not benifit much from this session.
    

### Problem 1: Add two randomly generated NumPy matrices using loops 
    - Sub-problems
    - Subproblems ---> coding concepts
    - Code-walkthrough + Mistakes
    - Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

In [1]:
# create random matrix A1 of size 5X4.
### Google " numpy create random matrices " & Read through the top 4-5 links
### https://www.codespeedy.com/how-to-create-matrix-of-random-numbers-in-python-numpy/

import numpy as np
A1 = np.random.rand(5,4) # read documentation to understand the params. Google "np.random.rand reference" ---> https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html

##COMMON-ERROR: np.random.rand(4,5)
##COMMON_ERROR: 

print(A1) # always print to ensure that everyhitng works fine.

print(A1.shape)


[[0.53153167 0.56879692 0.66940215 0.37073188]
 [0.25408113 0.96033642 0.42437323 0.1675077 ]
 [0.20972829 0.36897545 0.0177418  0.93687854]
 [0.289791   0.47874732 0.89232503 0.78670909]
 [0.00982236 0.46644229 0.79164288 0.45801251]]
(5, 4)


In [ ]:
print(A1.shape()); #COMMON-ERROR

TypeError: ignored

In [2]:
print(A1.type); # COMMON-ERROR

AttributeError: ignored

In [3]:
print(type(A1));

<class 'numpy.ndarray'>


In [ ]:
# Read through the attributes and methods in numpy.ndarray class
## Google "numpy.ndarray" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

## Pre-Google programmers: Read reference docs.

In [4]:
# Create random Matrix A2
A2 = np.random.rand(5,4);

print(A2);

[[0.69722336 0.49605012 0.42420779 0.87070976]
 [0.69003638 0.38511428 0.82111057 0.11374404]
 [0.41347018 0.02628718 0.29046345 0.15422512]
 [0.96479097 0.28143586 0.23373136 0.86639969]
 [0.51060547 0.56132075 0.61008838 0.67823643]]


In [5]:
# Add element wise using loops A1+A2 = B

## Google "Accessing i,j th element in an ndarray" ---> https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html
print(A1[2,3]);


0.9368785372346667


In [6]:
print(A1(2,3)); #COMMON_ERROR

TypeError: ignored

In [7]:
B= A1+A2; # using + operator on ndarrays
print(B); 

[[1.22875503 1.06484703 1.09360994 1.24144164]
 [0.94411751 1.3454507  1.24548381 0.28125174]
 [0.62319846 0.39526262 0.30820526 1.09110366]
 [1.25458197 0.76018318 1.12605639 1.65310878]
 [0.52042783 1.02776303 1.40173127 1.13624893]]


In [8]:
(r,c) = A1.shape;
print(r,c)

5 4


In [ ]:
#B[i,j] = A1[i,j] + A2 [i,j] 

for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

In [ ]:
# OPTIMIZATION: Pre-allocate matrix B
B = np.zeros(5,4); # COMMON-ERROR

In [ ]:
#Google "np.zeros" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html
B = np.zeros((5,4))

for i in range(r): # same code as earlier
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

In [ ]:
# Time Complexity: ?
# Space Complxiety: ?

#### Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]
****************************************************************************************************************
****************************************************************************************************************
****************************************************************************************************************

### Problem 2: Find if a given 2D-point is inside (or) outside a circle 
    - Subproblems.
    - Subproblems --> coding concepts.
    - putting it all together.
    - Exercise: Find if a given 2D point is inside (or) outside a rectangle ? 
   

In [ ]:
## input circle (C) and point(P)

# input circle params
# Google " input multiple values python 3" ---> https://www.geeksforgeeks.org/input-multiple-values-user-one-line-python/
print("Enter Cx, Cy, r:");
(Cx, Cy, r) = raw_input().split();

print(Cx, Cy, r); # always cross check using print statements

Enter Cx, Cy, r:


KeyboardInterrupt: 

In [ ]:
# input circle params
## Google "python input multiple values in single line" ----> https://www.tutorialspoint.com/how-to-input-multiple-values-from-user-in-one-line-in-python
## TRY MULTIPLE APPROACHES and learn from each attempt.

Cx, Cy, r = input("Enter Cx, Cy, r:").split();
print(Cx, Cy, r)


Enter Cx, Cy, r:0.0 0.0 0.5
0.0 0.0 0.5


In [ ]:
# Google " SyntaxError: invalid syntax input Python3 string" --> https://stackoverflow.com/questions/25174925/syntax-error-for-input
Cx, Cy, r = raw_input("Enter Cx, Cy, r:").split();


NameError: ignored

In [ ]:
print(Cx, Cy,r)

('0.0', '0.0', '5.0')


In [ ]:
# Input Px, Py

Px, Py = raw_input("Enter Px, Py:").split()
print(Px, Py);

Enter Px, Py:1.0 1.0
('1.0', '1.0')


In [ ]:
# Check if P lies in C.
d = ( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
# Check if P lies in C.

## String to Float. Very important to note that split() returns Strings
Cx = float(Cx);
Cy = float(Cy);
r =float(r);
Px= float(Px);
Py = float(Py);

import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

1.41421356237
P in C


#### Exercise: Find if a point is inside or outside a rectangle.

HINT: How do you represent a rectangle?

********************************************
********************************************
********************************************

### Problem 3: NumPy ndarray manupualtion operations


In [ ]:
# 1. Reshape matrices: Very COMMON-ERRORS in Assignments
A = np.random.rand(5,4);
print(A);


[[0.14807421 0.76465119 0.35072274 0.44772859]
 [0.76310969 0.60355746 0.39205106 0.55551216]
 [0.52171983 0.14015325 0.07435462 0.84967035]
 [0.31052941 0.57171621 0.36938534 0.92015166]
 [0.14458459 0.12976042 0.4790811  0.98251111]]


In [9]:
## reshape into a vector row-major-order
###https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html 
### Patiently read the documentation and try alternaive params
print( np.reshape(A, 20, 'C'))


NameError: ignored

In [ ]:
print( np.reshape(A, 20, 'F'))

[0.14807421 0.76310969 0.52171983 0.31052941 0.14458459 0.76465119
 0.60355746 0.14015325 0.57171621 0.12976042 0.35072274 0.39205106
 0.07435462 0.36938534 0.4790811  0.44772859 0.55551216 0.84967035
 0.92015166 0.98251111]


In [ ]:
print( np.reshape(A, (4,5), 'C'))

[[0.14807421 0.76465119 0.35072274 0.44772859 0.76310969]
 [0.60355746 0.39205106 0.55551216 0.52171983 0.14015325]
 [0.07435462 0.84967035 0.31052941 0.57171621 0.36938534]
 [0.92015166 0.14458459 0.12976042 0.4790811  0.98251111]]


In [ ]:
print( np.reshape(A, (4,-1), 'C'))

[[0.14807421 0.76465119 0.35072274 0.44772859 0.76310969]
 [0.60355746 0.39205106 0.55551216 0.52171983 0.14015325]
 [0.07435462 0.84967035 0.31052941 0.57171621 0.36938534]
 [0.92015166 0.14458459 0.12976042 0.4790811  0.98251111]]


In [ ]:
print( np.reshape(A, (-1,5), 'C'))

[[0.14807421 0.76465119 0.35072274 0.44772859 0.76310969]
 [0.60355746 0.39205106 0.55551216 0.52171983 0.14015325]
 [0.07435462 0.84967035 0.31052941 0.57171621 0.36938534]
 [0.92015166 0.14458459 0.12976042 0.4790811  0.98251111]]


In [ ]:
print( np.reshape(A, (4,6), 'C'))

ValueError: cannot reshape array of size 20 into shape (4,6)

#### Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector and matrix (10X12).

In [ ]:
#2. Stacking
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)


[[0.4543747  0.64690556 0.01325659 0.4005741 ]
 [0.37270572 0.9229127  0.11746422 0.23759922]
 [0.91889495 0.53198908 0.40542735 0.57103514]
 [0.2562349  0.96441954 0.77128697 0.98914802]
 [0.5388144  0.79256948 0.58861248 0.5072647 ]]
[[0.93198709 0.02293127]
 [0.84602856 0.18276059]
 [0.00741556 0.54525969]
 [0.33630522 0.79257607]
 [0.00361456 0.58644709]]


In [ ]:
# C = [A B]
C = np.hstack(A, B);
print(C)

TypeError: hstack() takes exactly 1 argument (2 given)

In [ ]:
C = np.hstack((A, B)); # read documentation carefully
print(C)

[[0.4543747  0.64690556 0.01325659 0.4005741  0.93198709 0.02293127]
 [0.37270572 0.9229127  0.11746422 0.23759922 0.84602856 0.18276059]
 [0.91889495 0.53198908 0.40542735 0.57103514 0.00741556 0.54525969]
 [0.2562349  0.96441954 0.77128697 0.98914802 0.33630522 0.79257607]
 [0.5388144  0.79256948 0.58861248 0.5072647  0.00361456 0.58644709]]


In [ ]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.hstack((A, B));
print(C)

[[0.07442156 0.90842643 0.26791901 0.52103986]
 [0.31627629 0.96720084 0.92801681 0.29094456]
 [0.92762484 0.2036012  0.62790382 0.21155578]
 [0.03114235 0.02227744 0.45126548 0.07824812]
 [0.31206675 0.12787428 0.78704942 0.95472092]]
[[0.74204087 0.3375716  0.53499921 0.64780102]
 [0.95762786 0.35441587 0.99187725 0.38097213]
 [0.34547302 0.48853482 0.85121261 0.81847693]
 [0.1783305  0.40696326 0.71089858 0.49241374]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.vstack((A, B)); #Vertical stacking
print(C)

[[0.47572417 0.88468831 0.81030914 0.54286827]
 [0.088576   0.6447609  0.65370572 0.31849572]
 [0.01805613 0.46166837 0.4602457  0.35788657]
 [0.37245741 0.49461568 0.31431636 0.3799997 ]
 [0.96098487 0.1608441  0.50098802 0.01518362]]
[[0.43308702 0.04543804 0.91316269 0.86101818]
 [0.86514807 0.63395249 0.40368305 0.31388662]
 [0.82764524 0.15498427 0.70440415 0.904619  ]
 [0.13671617 0.81722549 0.95948317 0.70652946]]
[[0.47572417 0.88468831 0.81030914 0.54286827]
 [0.088576   0.6447609  0.65370572 0.31849572]
 [0.01805613 0.46166837 0.4602457  0.35788657]
 [0.37245741 0.49461568 0.31431636 0.3799997 ]
 [0.96098487 0.1608441  0.50098802 0.01518362]
 [0.43308702 0.04543804 0.91316269 0.86101818]
 [0.86514807 0.63395249 0.40368305 0.31388662]
 [0.82764524 0.15498427 0.70440415 0.904619  ]
 [0.13671617 0.81722549 0.95948317 0.70652946]]


In [ ]:
# 3D tensors
A = np.random.rand(5,4,3); # (height, width, colors) in images is a good way to think of this
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)


In [ ]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(4,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(4, 3, 3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(5,4,2);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 4, 2)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
# 3D tensors vstack
A = np.random.rand(5,4,3); # (height, width, colors) in images
print(A.shape);

B= np.random.rand(2,4,3);
print(B.shape)

C = np.vstack((A, B));
print(C.shape)

(5, 4, 3)
(2, 4, 3)
(7, 4, 3)


#### Exercise: Achieve the above tranaomfrs using numpy.concatenate [https://numpy.org/doc/1.18/reference/generated/numpy.concatenate.html#numpy.concatenate]
***********
***********
***********
***********


### Problem-4: Find peaks/max in an list
- problem definition


In [ ]:

A = [1,3,4,5,7,6,4,5,10,1];
print(A)

[1, 3, 4, 5, 7, 6, 4, 5, 10, 1]


In [ ]:
# Peaks: 7,10
# Peak: A[i-1] <= A[i] >= A[i+1]

for i in range(1, A.size - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

AttributeError: 'list' object has no attribute 'size'

In [ ]:
print(len(A));

10


In [ ]:
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7
10


In [ ]:
# There is a bug in the above solution. Find it...


In [ ]:
A = [11,3,4,5,7,6,4,5,10,15];

for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7


In [ ]:
# what about 11 and 15?

# boundary case
if A[0] >= A[1]:
    print(A[0])
    
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

# boundary case
if A[len(A)-1] >= A[len(A)-2]:
    print(A[len(A)-1])


In [ ]:
# LESSON: Donot forget boundary cases

#Question: Time Complexity = ?

#### Exercise: 
1. Find peaks which are max values in a window of size 2 on both sides.
2. Use scipy.signal.find_peaks [https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html]

Additioanl reading: More efficient algos @ http://courses.csail.mit.edu/6.006/spring11/lectures/lec02.pdf

### Problem 5: Permutations of a list
- Problem definition: lst = [1,2,3]

In [ ]:
# Using libraries
from itertools import permutations 
  
p = permutations([1, 2, 3]) # refer: https://docs.python.org/3/library/itertools.html#itertools.permutations

# what is an iterable in Python [https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Iterables.html]

# print the permutations
for i in list(p): 
    print i 

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [ ]:
# No fun!
# Write your own code. Any suggestions?
# Break the problem into smaller sub-problems

In [ ]:
[1,2,3]
[1,3,2]
[2,1,3]
[2,3,1]
[3,1,2]
[3,2,1]

[3, 2, 1]

In [ ]:
# source: https://stackoverflow.com/questions/13109274/python-recursion-permutations

def permutation(s):
   if len(s) == 1:
     return [s]

   perm_list = [] # resulting list
   for a in s:
     remaining_elements = [x for x in s if x != a]
     z = permutation(remaining_elements) # permutations of sub-list

     for t in z:
       perm_list.append([a] + t)

   return perm_list

s = [1,2,3];
p = permutation(s);
print(p)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


#### Exercise: [Combinations] All possible ways to pick 3 elements out of 5 elements

- HINT: Use recursion.
- Google "combinations in Python"

### Practice, practice and practice..

- Optional  Assignments at AAIC: https://go.aws/2JrmV4A [Functions] , https://drive.google.com/file/d/1VB3wJSt_Mq0HLP9uaqgsZBR4BLMFnkmY/view [Pandas]

- Basic Python: https://www.geeksforgeeks.org/python-programming-examples/
- NumPy: https://www.w3resource.com/python-exercises/numpy/index.php


In [11]:
x = "230"

In [12]:
x = x.ljust(6,"1")
x

'230111'

In [13]:
x.rstrip("1")

'230'